# ansible_inventory.tf
#
# Renders ansible/inventory.ini from live Terraform state, so the inventory
# never drifts from what's actually deployed. Per aws_design.md §10 — this
# closes the Terraform -> Ansible loop without needing dynamic inventory.
#
# The file lives at ../ansible/inventory.ini (one level above infra/). It is
# committed to git; Ansible-from-jump reads it directly after `git pull`.

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"

  content = <<-EOT
    # AUTO-GENERATED by Terraform. Edit infra/10_ansible_inventory.tf, not this file.
    #
    # Group naming convention: plural role names ([jumps], [lbs], ...) so they
    # never collide with single-host names (the "Found both group and host with
    # same name" warning).

    [jumps]
    jump ansible_host=${aws_instance.jump.private_ip}

    [lbs]
    lb ansible_host=${aws_instance.lb.private_ip}

    [app_canary]
    app-vm1 ansible_host=${aws_instance.app_vm1.private_ip}

    [app_stable]
    app-vm2 ansible_host=${aws_instance.app_vm2.private_ip}

    [apps:children]
    app_canary
    app_stable

    [mons]
    mon ansible_host=${aws_instance.mon.private_ip}

    [fleet:children]
    lbs
    apps
    mons

    [all:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=~/.ssh/${local.project_name}.pem
    ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
    # Pin Python to the /usr/bin/python3 symlink so minor-version bumps don't
    # change interpreter discovery.
    ansible_python_interpreter=/usr/bin/python3
  EOT
}
